### ISSUE TITLE
[FEAT] Main Routine

### ISSUE THREAD

**Issue by eldeshue** [eldeshue/miniRT#16]
## Description
프로그램의 main 루틴. 입력 매개변수를 분석하고 자원을 획득하며 렌더링을 수행하고 자원을 해소함.
## Todo
- [ ] 자원 초기화
- [ ] 프로그램 매개변수 분석
- [ ] *.rt 파일 파싱 루틴 호출
- [ ] 렌더링 루틴 호출
- [ ] 자원 삭제
## ETC
이후 파싱, 렌더링, 이미지 모듈 구현 필요.
