### ISSUE TITLE
[bug fix] Bug identified from test 1

### ISSUE THREAD

**Issue by eldeshue** [eldeshue/miniRT#25]
## Description
test1에서 식별된 버그에 대한 fix.

## Todo
- [x] Makefile의 파일 이름 변경, collider_utils
- [x] trace_ray에서 발생하는 segfault : t_material *m 초기화 중 nullptr 참조
- [x] t_material의 잘못된 변수명 : amb_color -> obj_color
- [x] trace ray의 base_color 수정
- [x] render_rt_window 의 무한 루프 : 인덱스 증가 없음.
- [x] render_window의 get_git_per_ray에서 t_rt_obj 핸들 획득 시 더블 포인터 역참조 미수행
- [x] render_resource 의 set_view_plane 호출 시점 이동. init_resource에서 수행해야 함.
- [x] trace_ray의 m에서 잘못된 포인터 참조.

## ETC
