### ISSUE TITLE
[Bug Fix] Colliders

### ISSUE THREAD

**Issue by eldeshue** [eldeshue/miniRT#31]
## Description
렌더링 과정에서 식별한 특정 상황에 대한 버그의 해결을 위한 이슈. 

## Todo
- [x] 실린더와 평면 사이의 간섭 -> 충돌 지점과 광원 사이의 거리가 평면보다 가까운 경우 발생함.
- [ ] 원뿔에서 밑면에 그림자가 지는 에러
- [ ] 원뿔에서 윗면 셰이딩 안되는 에러
- [x] 원뿔의 높이가 특정 이상이면, 법선 벡터가 사라지는 에러
- [ ] 코드 리팩토링
