### ISSUE TITLE
[Refactoring] refactor 1.

### ISSUE THREAD

**Issue by eldeshue** [eldeshue/miniRT#38]
## Description
프로젝트 제출을 위한 리팩토링 및 실행 과정 평가
## Todo
- [ ] material의 쓸모 없는 field들 삭제.
- [ ] 안티 앨리어싱 관련 코드 삭제.
- [ ] 실행 내용 평가
